"""Create initial tables

Revision ID: 4cc77a7191ea
Revises: 
Create Date: 2025-10-16 15:24:11.920943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cc77a7191ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contentid', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('event_start_date', sa.Date(), nullable=False),
    sa.Column('event_end_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_festivals_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_festivals'))
    )
    op.create_index('idx_festivals_title_date', 'festivals', ['title', 'event_start_date'], unique=False)
    op.create_index(op.f('ix_festivals_contentid'), 'festivals', ['contentid'], unique=True)
    op.create_index(op.f('ix_festivals_id'), 'festivals', ['id'], unique=False)
    op.create_index(op.f('ix_festivals_region_id'), 'festivals', ['region_id'], unique=False)
    op.create_index(op.f('ix_festivals_title'), 'festivals', ['title'], unique=False)
    op.alter_column('cart_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('markets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('markets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('wishlist_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('markets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=True)
    op.alter_column('markets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('cart_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_index(op.f('ix_festivals_title'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_region_id'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_id'), table_name='festivals')
    op.drop_index(op.f('ix_festivals_contentid'), table_name='festivals')
    op.drop_index('idx_festivals_title_date', table_name='festivals')
    op.drop_table('festivals')
    # ### end Alembic commands ###
