"""새로운 변경사항 메모

Revision ID: 69cf631fe639
Revises: cab00a13d2bb
Create Date: 2025-09-23 22:09:27.429287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cf631fe639'
down_revision: Union[str, Sequence[str], None] = 'cab00a13d2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contentid', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_festivals_contentid'), ['contentid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_festivals_contentid'))
        batch_op.drop_column('contentid')

    # ### end Alembic commands ###
