"""Create tour_data table

Revision ID: d44e2f988099
Revises: cab00a13d2bb
Create Date: 2025-10-02 14:19:25.333855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44e2f988099'
down_revision: Union[str, Sequence[str], None] = 'cab00a13d2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contentid', sa.String(length=20), nullable=False),
    sa.Column('contenttypeid', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('addr1', sa.String(length=255), nullable=True),
    sa.Column('addr2', sa.String(length=255), nullable=True),
    sa.Column('areacode', sa.String(length=5), nullable=True),
    sa.Column('sigungucode', sa.String(length=5), nullable=True),
    sa.Column('tel', sa.String(length=100), nullable=True),
    sa.Column('firstimage', sa.Text(), nullable=True),
    sa.Column('firstimage2', sa.Text(), nullable=True),
    sa.Column('mapx', sa.Float(), nullable=True),
    sa.Column('mapy', sa.Float(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('cat1', sa.String(length=10), nullable=True),
    sa.Column('cat2', sa.String(length=10), nullable=True),
    sa.Column('cat3', sa.String(length=10), nullable=True),
    sa.Column('booktour', sa.String(length=5), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_data')),
    sa.UniqueConstraint('contentid', name=op.f('uq_tour_data_contentid'))
    )
    with op.batch_alter_table('tour_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_data_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_data_id'))

    op.drop_table('tour_data')
    # ### end Alembic commands ###
