# app/models/__init__.py
from app.db.database import Base

# 아래 import들이 실제로 테이블 클래스를 메모리에 로드하게 함
from .market_models import *        # Market, Product, Category, Region ...
from .festival_models import *      # Festival, Event ...
from .recommend_models import *     # User, Keyword, RecommendLog ...
from .users_models import User
